name: Go Test

on:
  push:
    branches:
      - main  # Trigger on push to main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.23.4

      - name: Install dependencies
        working-directory: ${{ github.workspace }}/odyscan
        run: go mod tidy

      - name: Run tests
        working-directory: ${{ github.workspace }}/odyscan/scanner
        run: go test ./... -v
